# Generated by Django 4.0.3 on 2022-05-14 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_resort_remove_user_favouriteresorts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
