# Generated by Django 4.0.3 on 2022-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_resort_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='address',
        ),
        migrations.AddField(
            model_name='resort',
            name='image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
