# Generated by Django 4.0.3 on 2022-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_resort_address_resort_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='resort',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
    ]
