# Generated by Django 4.0.3 on 2022-04-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('favouriteResorts', models.IntegerField()),
            ],
        ),
    ]
